version: 2
jobs:
  maven/test:
    docker:
    - image: circleci/openjdk:8-jdk-node
    steps:
    - checkout
    - run:
        name: Generate Cache Checksum
        command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
    - restore_cache:
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    - run:
        name: Install Dependencies
        command: mvn clean install -DskipTests=true --settings 'pom.xml' -X
    - run:
        name: Run Tests
        command: mvn verify --settings 'pom.xml'
    - save_cache:
        paths:
            - ~/.m2
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    - run:
        name: Save test results
        command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*txt" -exec cp {} ~/test-results/junit/ \;
            find . -type f -regex ".*/target/.*jar" -exec cp {} ~/test-results/junit/ \;
        when: always
    - store_test_results:
        path: ~/test-results
    - store_artifacts:
        path: ~/test-results/junit   
workflows:
  maven_test:
    jobs:
    - maven/test
  version: 2